server:
  port: 8080
spring:
#  application:
#    name: dztmall
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/dztmall
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis-plus:
  mapper-locations: classpath:mappers/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl